<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUgrt7Z3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUgrt7Z3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUgrt7Z3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUgrt7Z3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUgrt7Z3\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ugrt7Z3',
    'container.build_id' => '71198b00',
    'container.build_time' => 1646208472,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUgrt7Z3');
