<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDycyMIH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDycyMIH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDycyMIH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDycyMIH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDycyMIH\App_KernelDevDebugContainer([
    'container.build_hash' => 'DycyMIH',
    'container.build_id' => '5732a5d0',
    'container.build_time' => 1645873223,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDycyMIH');
