<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFzwxmbL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFzwxmbL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFzwxmbL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFzwxmbL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFzwxmbL\App_KernelDevDebugContainer([
    'container.build_hash' => 'FzwxmbL',
    'container.build_id' => '68f731f6',
    'container.build_time' => 1646059352,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFzwxmbL');
