<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'dashboard' => [[], ['_controller' => 'App\\Controller\\DashboardController::index'], [], [['text', '/dashboard']], [], [], []],
    'dashboard.delete' => [['id'], ['_controller' => 'App\\Controller\\DashboardController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/dashboard/delete']], [], [], []],
    'dashboard.create' => [[], ['_controller' => 'App\\Controller\\DashboardController::add'], [], [['text', '/dashboard/create']], [], [], []],
    'dashboard.edit' => [['id'], ['_controller' => 'App\\Controller\\DashboardController::edit'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/dashboard/edit']], [], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], [], []],
    'shop' => [[], ['_controller' => 'App\\Controller\\HomeController::shop'], [], [['text', '/shop']], [], [], []],
    'recherche' => [[], ['_controller' => 'App\\Controller\\HomeController::recherche'], [], [['text', '/recherche']], [], [], []],
    'recherche.categorie' => [['name'], ['_controller' => 'App\\Controller\\HomeController::categorie'], [], [['variable', '/', '[^/]++', 'name', true], ['text', '/categorie']], [], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], [], []],
];
