<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFdPKvca\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFdPKvca/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFdPKvca.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFdPKvca\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFdPKvca\App_KernelDevDebugContainer([
    'container.build_hash' => 'FdPKvca',
    'container.build_id' => '4c0084ee',
    'container.build_time' => 1646231249,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFdPKvca');
